# site settings
title: Portfolio
subtitle: Home
email: patrick.ritchie89@gmail.com
description: Welcome to my web portfolio site<br /> go ahead and click-about.
baseurl: "/wd6portfolio" # the subpath of your site, e.g. /blog
url: # the base hostname & protocol for your site
author:
street_address:
city: Orlando
state: FL
zip_code: 32792
country: United States of America
phone: (260) 341-0119

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings
500px_url:
facebook_url:
github_url: https://github.com/pmritchie
gitlab_url: 
googleplus_url: 
instagram_url: 
linkedin_url: https://www.linkedin.com/in/patrick-ritchie89/
pinterest_url:
slack_url:
twitter_url: 

# build settings
markdown: kramdown

sass:
  style: compressed
